//Menu Icon Constants
export const ICON_MENU = "ICON_MENU";
export const ICON_OPTIONS = "ICON_OPTIONS";
export const ICON_TROPHY = "ICON_TROPHY";
export const ICON_CLOSE = "ICON_CLOSE";

//Color Constants
export const COLOR_LIGHT1 = "COLOR_LIGHT1";
export const COLOR_LIGHT2 = "COLOR_LIGHT2";
export const COLOR_LIGHT3 = "COLOR_LIGHT3";

export const COLOR_LIGHT_TRANSPARENT1 = "COLOR_LIGHT_TRANSPARENT1";
export const COLOR_LIGHT_TRANSPARENT2 = "COLOR_LIGHT_TRANSPARENT2";
export const COLOR_LIGHT_TRANSPARENT3 = "COLOR_LIGHT_TRANSPARENT3";
export const COLOR_LIGHT_TRANSPARENT4 = "COLOR_LIGHT_TRANSPARENT4";
export const COLOR_LIGHT_TRANSPARENT5 = "COLOR_LIGHT_TRANSPARENT5";

export const COLOR_DARK1 = "COLOR_DARK1";
export const COLOR_DARK2 = "COLOR_DARK2";
export const COLOR_DARK3 = "COLOR_DARK3";

export const COLOR_DARK_TRANSPARENT1 = "COLOR_DARK_TRANSPARENT1";
export const COLOR_DARK_TRANSPARENT2 = "COLOR_DARK_TRANSPARENT2";
export const COLOR_DARK_TRANSPARENT3 = "COLOR_DARK_TRANSPARENT3";
export const COLOR_DARK_TRANSPARENT4 = "COLOR_DARK_TRANSPARENT4";
export const COLOR_DARK_TRANSPARENT5 = "COLOR_DARK_TRANSPARENT5";

//Other Colors
export const COLOR_SUCCESS = "COLOR_SUCCESS";
export const COLOR_DANGER = "COLOR_DANGER";
export const COLOR_ACCENT = "COLOR_ACCENT";
export const COLOR_GOLD = "COLOR_GOLD";
