export const SORT_GAMES_COMPLETION = "SORT_GAMES_COMPLETION";
export const SORT_GAMES_NAMES_AZ = "SORT_GAMES_NAMES_AZ";
export const SORT_GAMES_NAMES_ZA = "SORT_GAMES_NAMES_ZA";

export const SORT_ACHIEVEMENTS_ALL = "SORT_ACHIEVEMENTS_ALL";
export const SORT_ACHIEVEMENTS_LOCKED = "SORT_ACHIEVEMENTS_LOCKED";
export const SORT_ACHIEVEMENTS_UNLOCKED = "SORT_ACHIEVEMENTS_UNLOCKED";
