export const SORT_GAMES_COMPLETION = "SORT_GAMES_COMPLETION";
export const SORT_GAMES_NAMES_AZ = "SORT_GAMES_NAMES_AZ";
export const SORT_GAMES_NAMES_ZA = "SORT_GAMES_NAMES_ZA";

export const SORT_ACHIEVEMENTS_ALL = "SORT_ACHIEVEMENTS_ALL";
export const SORT_ACHIEVEMENTS_LOCKED = "SORT_ACHIEVEMENTS_LOCKED";
export const SORT_ACHIEVEMENTS_UNLOCKED = "SORT_ACHIEVEMENTS_UNLOCKED";

export const GAME_VIEW_TYPE_LARGE = "GAME_VIEW_TYPE_LARGE";
export const GAME_VIEW_TYPE_SMALL = "GAME_VIEW_TYPE_SMALL";
export const GAME_VIEW_TYPE_ICON = "GAME_VIEW_TYPE_ICON";

export const RECENT_TYPE_TODAY = "RECENT_TYPE_TODAY";
export const RECENT_TYPE_WEEK = "RECENT_TYPE_WEEK";
export const RECENT_TYPE_MONTH = "RECENT_TYPE_MONTH";
export const RECENT_TYPE_YEAR = "RECENT_TYPE_YEAR";
