export const HEADER_LEFT_GAMES_ON = "HEADER_LEFT_GAMES_ON";
export const HEADER_RIGHT_GAMES_ON = "HEADER_RIGHT_GAMES_ON";
export const HEADER_LEFT_GAMES_OFF = "HEADER_LEFT_GAMES_OFF";
export const HEADER_RIGHT_GAMES_OFF = "HEADER_RIGHT_GAMES_OFF";
