export const GAMES_PAGE_SELECTED_GAME = "GAMES_PAGE_SELECTED_GAME";
export const GAMES_PAGE_SEARCH_TERM = "GAMES_PAGE_SEARCH_TERM";
export const GAMES_PAGE_DRAWER_TOGGLE = "GAMES_PAGE_DRAWER_TOGGLE";
export const GAMES_PAGE_SEARCH_SHOW = "GAMES_PAGE_SEARCH_SHOW";
export const GAMES_PAGE_TOGGLE_OPTIONS = "GAMES_PAGE_TOGGLE_OPTIONS";
export const GAMES_PAGE_SORT_OPTIONS = "GAMES_PAGE_SORT_OPTIONS";

export const GAME_PAGE_SELECTED_GAME = "GAME_PAGE_SELECTED_GAME";
export const GAME_PAGE_SEARCH_TERM = "GAME_PAGE_SEARCH_TERM";
export const GAME_PAGE_DRAWER_TOGGLE = "GAME_PAGE_DRAWER_TOGGLE";
export const GAME_PAGE_SEARCH_SHOW = "GAME_PAGE_SEARCH_SHOW";
export const GAME_PAGE_TOGGLE_COMPLETED = "GAME_PAGE_TOGGLE_COMPLETED";
export const GAME_PAGE_TOGGLE_OPTIONS = "GAME_PAGE_TOGGLE_OPTIONS";
export const GAME_PAGE_SORT_OPTIONS = "GAME_PAGE_SORT_OPTIONS";
