export const GAMES_PAGE_SELECTED_GAME = "GAMES_PAGE_SELECTED_GAME";
export const GAMES_PAGE_SEARCH_TERM = "GAMES_PAGE_SEARCH_TERM";
export const GAMES_PAGE_DRAWER_TOGGLE = "GAMES_PAGE_DRAWER_TOGGLE";
export const GAMES_PAGE_SEARCH_SHOW = "GAMES_PAGE_SEARCH_SHOW";
