export const FETCH_ALL_GAMES_REQUEST = "FETCH_ALL_GAMES_REQUEST";
export const FETCH_ALL_GAMES_SUCCESS = "FETCH_ALL_GAMES_SUCCESS";
export const FETCH_ALL_GAMES_ERROR = "FETCH_ALL_GAMES_ERROR";
export const REFRESH_GAME_DATA = "REFRESH_GAME_DATA";

export const SET_HIDDEN_ACHIEVEMENTS_GAME = "SET_HIDDEN_ACHIEVEMENTS_GAME";
